### PR TITLE
Improved M1 Macs Compatibility

### PR DESCRIPTION
**Pull request by ghost**
- Updated using Ukelele Version 3.5.2 (343)
- Improved M1 Macs compatibility
- tested on MBA M1

### CODE REVIEW

**Comment by akaDuality** [comment]
Have tested on BigSur, but not on M1, [the installation problem](https://github.com/MadRabbit/halmak/issues) has gone

**Comment by akaDuality** [comment]
Unfortunately, all CMD-modifiers that changes to QWERTY is lost

**Comment by ghost** [comment]
> Unfortunately, all CMD-modifiers that changes to QWERTY is lost

Should be good now. Thanks for the heads up.

**Comment by akaDuality** [comment]
Thank you! I will test all this week

**Pull request closed without merging**
